# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Execute Job
  # You may pin to the exact commit or the version.
  # uses: parasoft/execute-job-action@c02b0c00163aef3e2099076026ca79cf5bdc26a6
        uses: parasoft/execute-job-action@1.0.3
        with:
          # CTP URL
          ctpUrl: 35.167.69.93
          # CTP Username
          ctpUsername: demo
          # CTP Password
          ctpPassword: demo-user
          # CTP Test Execution Job Name
          ctpJob: P1 Smoke Tests
          # Abort the job after timeout exceeded
          #abortOnTimeout: # optional
          # Timeout value in minutes
          #timeoutInMinutes: # optional
          # Publish test execution results to DTP
          #publishReport: # optional
          # DTP URL
          #dtpUrl: # optional
          # DTP Username
          #dtpUsername: # optional
          # DTP Password
          #dtpPassword: # optional
          # DTP Project Name
          #dtpProject: # optional
          # Build ID to send to DTP
          #buildId: # optional
          # Session Tag to send to DTP
          #sessionTag: # optional
          # Append the test variable set environment name to the session tag
          #appendEnvironment: # optional






